services:
  grant-api:
    container_name: grant-api
    build: .
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgres://user:password@db:5432/grantsdb'
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grantsdb
    ports:
      - '5432:5432'
